name: bento
description: A new way of defining widgets.
version: 0.0.1+alpha
homepage: https://github.com/aloisdeniel/bento

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  collection: ^1.16.0
  analyzer: ^4.0.0
  code_builder: ^4.1.0
  recase: ^4.0.0
  dart_style: ^2.2.3
  path: ^1.8.1
  yaml: ^3.1.1
  args: ^2.3.1

dev_dependencies:
  freezed: ^2.0.3+1
  build_runner: ^2.0.0
  json_serializable: ^6.2.0
  test: ^1.21.1
  lints: ^2.0.0
